Resources:
  security: 
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: creating a first securitygroup
      GroupName: firstgroup
      SecurityGroupEgress:
       - IpProtocol: -1
         FromPort: -1
         ToPort: -1
         CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
      VpcId: "vpc-05c5d6c996ae6df77"    